#!/bin/bash
printf "\n"
echo -e "\e[40m\e[32m░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░\e[0m"
echo -e "\e[40m\e[32m░░                                                                                     ░░\e[0m"
echo -e "\e[40m\e[32m░░     ╔╝█████ ╔╝███████ ╔╝███╔═╝███ ╔╝██████ ╔╝████╔╝██ ╔╝█████  ╔╝███████  ║█████    ░░\e[0m"
echo -e "\e[40m\e[32m░░    ╔╝██    ╔╝██ ╔╝██ ╔╝████║████ ╔╝██ ║██ ╔╝██║██║██ ╔╝██╔╝██ ╔╝██ ╔╝██   ║██       ░░\e[0m"
echo -e "\e[40m\e[32m░░   ╔╝██    ╔╝██  ║██ ╔╝██ ███ ██ ╔╝██████ ╔╝██ ║████ ╔╝██ ║██ ╔╝██  ║██ ╔══╝██       ░░\e[0m"
echo -e "\e[40m\e[32m░░   ║█████  ║███████  ║██    ║██  ║██ ║██  ║██  ║███  ║█████   ║███████  ║█████       ░░\e[0m"
echo -e "\e[40m\e[32m░░                                                                                     ░░\e[0m"
echo -e "\e[40m\e[32m░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░\e[0m"
echo -e "\e[40m\e[32m░░                ░                                                                    ░░\e[0m"
echo -e "\e[40m\e[32m░░    ayuda       ░    Muestra los comandos disponibles además de los normales         ░░\e[0m"
echo -e "\e[40m\e[32m░░    infosis     ░    Muestra información del sistema (RAM,SO,Arquitectura)           ░░\e[0m"
echo -e "\e[40m\e[32m░░    time        ░    Te proporciona la fecha y hora actuales                         ░░\e[0m"
echo -e "\e[40m\e[32m░░    buscar      ░    Te permite saber si un archvio está en cierto directorio        ░░\e[0m"
echo -e "\e[40m\e[32m░░    creditos    ░    Te informa quienes realizamos este proyecto                     ░░\e[0m"
echo -e "\e[40m\e[32m░░    juego       ░    Inicia un juego de ahorcado contra nosotros >:)                 ░░\e[0m"
echo -e "\e[40m\e[32m░░    musica      ░    Ejecuta un reproductor mp3 para escuchar tu musikita            ░░\e[0m"
echo -e "\e[40m\e[32m░░    salir       ░    Esta es la forma de salir de esta cli, no hay de otra jiji      ░░\e[0m"
echo -e "\e[40m\e[32m░░                ░                                                                    ░░\e[0m"
echo -e "\e[40m\e[32m░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░\e[0m"
printf "\n"